site_name: InfoSchool Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro

nav:
  - Início: index.md

  - Arquitetura Back-end:
      - Arquitetura Geral: Arquitetura back-end/Arquitetura Geral.md
      - RAG (Retrieval-augmented generation): Arquitetura back-end/RAG (Retrieval-augmented generation) ....md

  - Arquitetura Front-end:
      - Arquitetura Frontend: arquitetura-frontend/arquitetura-frontend.md
      - Boas práticas: arquitetura-frontend/boas-praticas-documentacao.md
      - Next.js: arquitetura-frontend/next.md
      - Stack Tecnológica: arquitetura-frontend/stack-tecnologica.md

  - Atas:
      - Reunião 01: atas/ata_reuniao_01.md
      - Reunião 02: atas/ata_reuniao_02.md
      - Reunião 03: atas/ata_reuniao_03.md
      - Template de Ata: atas/template_ata.md

  - DevOps:
      - Comunicação Web HTTP: DevOps/comunicacao-web-HTTP.md
      - Docker: DevOps/Docker.md
      - Git + GitHub Pages: DevOps/Git-GitHub-GitPages.md
      - Linux: DevOps/linux.md

  - Estudos:
      - HTML e CSS: estudos/html_css.md
      - JavaScript: estudos/javascript.md
      - Node.js: estudos/Nodejs.md
      - Scrum Master: estudos/srum_master.md
