export const DICIONARIO_DADOS: Record<string, string> = {
    // IDENTIFICAÇÃO E LOCALIZAÇÃO
    "NU_ANO_CENSO": "Ano do Censo",
    "NO_REGIAO": "Região",
    "CO_REGIAO": "Cód. Região",
    "NO_UF": "Estado",
    "SG_UF": "UF",
    "CO_UF": "Cód. UF",
    "NO_MUNICIPIO": "Município",
    "CO_MUNICIPIO": "Cód. Município",
    "NO_REGIAO_GEOG_INTERM": "Região Geográfica Intermediária",
    "CO_REGIAO_GEOG_INTERM": "Cód. Região Intermediária",
    "NO_REGIAO_GEOG_IMED": "Região Geográfica Imediata",
    "CO_REGIAO_GEOG_IMED": "Cód. Região Imediata",
    "NO_MESORREGIAO": "Mesorregião",
    "CO_MESORREGIAO": "Cód. Mesorregião",
    "NO_MICRORREGIAO": "Microrregião",
    "CO_MICRORREGIAO": "Cód. Microrregião",
    "NO_DISTRITO": "Distrito",
    "CO_DISTRITO": "Cód. Distrito",
    "NO_ENTIDADE": "Nome da Escola",
    "CO_ENTIDADE": "Código INEP",
    "TP_DEPENDENCIA": "Dependência Administrativa",
    "TP_CATEGORIA_ESCOLA_PRIVADA": "Categoria Escola Privada",
    "TP_LOCALIZACAO": "Localização",
    "TP_LOCALIZACAO_DIFERENCIADA": "Localização Diferenciada",
    "DS_ENDERECO": "Endereço",
    "NU_ENDERECO": "Número",
    "DS_COMPLEMENTO": "Complemento",
    "NO_BAIRRO": "Bairro",
    "CO_CEP": "CEP",
    "NU_DDD": "DDD",
    "NU_TELEFONE": "Telefone",
    "TP_SITUACAO_FUNCIONAMENTO": "Situação de Funcionamento",
    "CO_ORGAO_REGIONAL": "Cód. Órgão Regional",
    "DT_ANO_LETIVO_INICIO": "Início Ano Letivo",
    "DT_ANO_LETIVO_TERMINO": "Término Ano Letivo",

    // VÍNCULOS E PARCERIAS
    "IN_VINCULO_SECRETARIA_EDUCACAO": "Vínculo Secretaria Educação",
    "IN_VINCULO_SEGURANCA_PUBLICA": "Vínculo Segurança Pública",
    "IN_VINCULO_SECRETARIA_SAUDE": "Vínculo Secretaria Saúde",
    "IN_VINCULO_OUTRO_ORGAO": "Vínculo Outro Órgão",
    "IN_PODER_PUBLICO_PARCERIA": "Parceria Poder Público",
    "TP_PODER_PUBLICO_PARCERIA": "Tipo Parceria Poder Público",
    "IN_FORMA_CONT_TERMO_COLABORA": "Termo de Colaboração",
    "IN_FORMA_CONT_TERMO_FOMENTO": "Termo de Fomento",
    "IN_FORMA_CONT_ACORDO_COOP": "Acordo de Cooperação",
    "IN_FORMA_CONT_PRESTACAO_SERV": "Prestação de Serviços",
    "IN_FORMA_CONT_COOP_TEC_FIN": "Cooperação Téc./Financ.",
    "IN_FORMA_CONT_CONSORCIO_PUB": "Consórcio Público",
    "IN_MANT_ESCOLA_PRIVADA_EMP": "Mantenedora Empresa",
    "IN_MANT_ESCOLA_PRIVADA_ONG": "Mantenedora ONG",
    "IN_MANT_ESCOLA_PRIVADA_OSCIP": "Mantenedora OSCIP",
    "IN_MANT_ESCOLA_PRIV_ONG_OSCIP": "Mantenedora ONG/OSCIP",
    "IN_MANT_ESCOLA_PRIVADA_SIND": "Mantenedora Sindicato",
    "IN_MANT_ESCOLA_PRIVADA_SIST_S": "Mantenedora Sistema S",
    "IN_MANT_ESCOLA_PRIVADA_S_FINS": "Mantenedora Sem Fins Lucrativos",
    "NU_CNPJ_ESCOLA_PRIVADA": "CNPJ Escola",
    "NU_CNPJ_MANTENEDORA": "CNPJ Mantenedora",
    "TP_REGULAMENTACAO": "Regulamentação",
    "TP_RESPONSAVEL_REGULAMENTACAO": "Responsável Regulamentação",
    "CO_ESCOLA_SEDE_VINCULADA": "Cód. Escola Sede",
    "CO_IES_OFERTANTE": "Cód. IES Ofertante",

    // INFRAESTRUTURA BÁSICA
    "IN_LOCAL_FUNC_PREDIO_ESCOLAR": "Prédio Escolar",
    "TP_OCUPACAO_PREDIO_ESCOLAR": "Ocupação Prédio",
    "IN_LOCAL_FUNC_SOCIOEDUCATIVO": "Unidade Socioeducativa",
    "IN_LOCAL_FUNC_UNID_PRISIONAL": "Unidade Prisional",
    "IN_LOCAL_FUNC_PRISIONAL_SOCIO": "Prisional/Socioeducativo",
    "IN_LOCAL_FUNC_GALPAO": "Galpão",
    "TP_OCUPACAO_GALPAO": "Ocupação Galpão",
    "IN_LOCAL_FUNC_SALAS_OUTRA_ESC": "Salas Outra Escola",
    "IN_LOCAL_FUNC_OUTROS": "Outros Locais",
    "IN_PREDIO_COMPARTILHADO": "Prédio Compartilhado",
    "IN_AGUA_POTAVEL": "Água Potável",
    "IN_AGUA_REDE_PUBLICA": "Água Rede Pública",
    "IN_AGUA_POCO_ARTESIANO": "Poço Artesiano",
    "IN_AGUA_CACIMBA": "Cacimba/Cisterna",
    "IN_AGUA_FONTE_RIO": "Fonte/Rio",
    "IN_AGUA_INEXISTENTE": "Sem Água",
    "IN_AGUA_CARRO_PIPA": "Carro Pipa",
    "IN_ENERGIA_REDE_PUBLICA": "Energia Rede Pública",
    "IN_ENERGIA_GERADOR_FOSSIL": "Gerador Fóssil",
    "IN_ENERGIA_RENOVAVEL": "Energia Renovável",
    "IN_ENERGIA_INEXISTENTE": "Sem Energia",
    "IN_ESGOTO_REDE_PUBLICA": "Esgoto Rede Pública",
    "IN_ESGOTO_FOSSA_SEPTICA": "Fossa Séptica",
    "IN_ESGOTO_FOSSA_COMUM": "Fossa Comum",
    "IN_ESGOTO_FOSSA": "Fossa",
    "IN_ESGOTO_INEXISTENTE": "Sem Esgoto",
    "IN_LIXO_SERVICO_COLETA": "Coleta de Lixo",
    "IN_LIXO_QUEIMA": "Queima Lixo",
    "IN_LIXO_ENTERRA": "Enterra Lixo",
    "IN_LIXO_DESTINO_FINAL_PUBLICO": "Destino Final Público",
    "IN_LIXO_DESCARTA_OUTRA_AREA": "Descarta Outra Área",
    "IN_TRATAMENTO_LIXO_SEPARACAO": "Separação Lixo",
    "IN_TRATAMENTO_LIXO_REUTILIZA": "Reutiliza Lixo",
    "IN_TRATAMENTO_LIXO_RECICLAGEM": "Reciclagem Lixo",
    "IN_TRATAMENTO_LIXO_INEXISTENTE": "Sem Tratamento Lixo",

    // DEPENDÊNCIAS
    "IN_ALMOXARIFADO": "Almoxarifado",
    "IN_AREA_VERDE": "Área Verde",
    "IN_AREA_PLANTIO": "Área de Plantio",
    "IN_AUDITORIO": "Auditório",
    "IN_BANHEIRO": "Banheiro",
    "IN_BANHEIRO_EI": "Banheiro Ed. Infantil",
    "IN_BANHEIRO_PNE": "Banheiro PNE",
    "IN_BANHEIRO_FUNCIONARIOS": "Banheiro Funcionários",
    "IN_BANHEIRO_CHUVEIRO": "Chuveiro",
    "IN_BIBLIOTECA": "Biblioteca",
    "IN_BIBLIOTECA_SALA_LEITURA": "Sala de Leitura (Biblio)",
    "IN_COZINHA": "Cozinha",
    "IN_DESPENSA": "Despensa",
    "IN_DORMITORIO_ALUNO": "Dormitório Aluno",
    "IN_DORMITORIO_PROFESSOR": "Dormitório Professor",
    "IN_LABORATORIO_CIENCIAS": "Lab. Ciências",
    "IN_LABORATORIO_INFORMATICA": "Lab. Informática",
    "IN_LABORATORIO_EDUC_PROF": "Lab. Educ. Profissional",
    "IN_PATIO_COBERTO": "Pátio Coberto",
    "IN_PATIO_DESCOBERTO": "Pátio Descoberto",
    "IN_PARQUE_INFANTIL": "Parque Infantil",
    "IN_PISCINA": "Piscina",
    "IN_QUADRA_ESPORTES": "Quadra Esportes",
    "IN_QUADRA_ESPORTES_COBERTA": "Quadra Coberta",
    "IN_QUADRA_ESPORTES_DESCOBERTA": "Quadra Descoberta",
    "IN_REFEITORIO": "Refeitório",
    "IN_SALA_ATELIE_ARTES": "Ateliê Artes",
    "IN_SALA_MUSICA_CORAL": "Sala Música/Coral",
    "IN_SALA_ESTUDIO_DANCA": "Estúdio Dança",
    "IN_SALA_MULTIUSO": "Sala Multiuso",
    "IN_SALA_ESTUDIO_GRAVACAO": "Estúdio Gravação",
    "IN_SALA_OFICINAS_EDUC_PROF": "Oficinas Educ. Prof.",
    "IN_SALA_DIRETORIA": "Sala Diretoria",
    "IN_SALA_LEITURA": "Sala Leitura",
    "IN_SALA_PROFESSOR": "Sala Professor",
    "IN_SALA_REPOUSO_ALUNO": "Sala Repouso Aluno",
    "IN_SECRETARIA": "Secretaria",
    "IN_SALA_ATENDIMENTO_ESPECIAL": "Sala AEE",
    "IN_TERREIRAO": "Terreirão",
    "IN_VIVEIRO": "Viveiro",
    "IN_DEPENDENCIAS_OUTRAS": "Outras Dependências",

    // ACESSIBILIDADE
    "IN_ACESSIBILIDADE_CORRIMAO": "Corrimão",
    "IN_ACESSIBILIDADE_ELEVADOR": "Elevador",
    "IN_ACESSIBILIDADE_PISOS_TATEIS": "Pisos Táteis",
    "IN_ACESSIBILIDADE_VAO_LIVRE": "Vão Livre",
    "IN_ACESSIBILIDADE_RAMPAS": "Rampas",
    "IN_ACESSIBILIDADE_SINAL_SONORO": "Sinal Sonoro",
    "IN_ACESSIBILIDADE_SINAL_TATIL": "Sinal Tátil",
    "IN_ACESSIBILIDADE_SINAL_VISUAL": "Sinal Visual",
    "IN_ACESSIBILIDADE_INEXISTENTE": "Sem Acessibilidade",
    "IN_ACESSIBILIDADE_SINALIZACAO": "Sinalização Acess.",

    // SALAS DE AULA
    "QT_SALAS_UTILIZADAS_DENTRO": "Salas Dentro Prédio",
    "QT_SALAS_UTILIZADAS_FORA": "Salas Fora Prédio",
    "QT_SALAS_UTILIZADAS": "Total Salas Utilizadas",
    "QT_SALAS_UTILIZA_CLIMATIZADAS": "Salas Climatizadas",
    "QT_SALAS_UTILIZADAS_ACESSIVEIS": "Salas Acessíveis",

    // EQUIPAMENTOS
    "IN_EQUIP_PARABOLICA": "Parabólica",
    "IN_COMPUTADOR": "Computadores",
    "IN_EQUIP_COPIADORA": "Copiadora",
    "IN_EQUIP_IMPRESSORA": "Impressora",
    "IN_EQUIP_IMPRESSORA_MULT": "Multifuncional",
    "IN_EQUIP_SCANNER": "Scanner",
    "IN_EQUIP_NENHUM": "Sem Equipamentos",
    "IN_EQUIP_DVD": "DVD",
    "QT_EQUIP_DVD": "Qtd. DVD",
    "IN_EQUIP_SOM": "Som",
    "QT_EQUIP_SOM": "Qtd. Som",
    "IN_EQUIP_TV": "TV",
    "QT_EQUIP_TV": "Qtd. TV",
    "IN_EQUIP_LOUSA_DIGITAL": "Lousa Digital",
    "QT_EQUIP_LOUSA_DIGITAL": "Qtd. Lousa Digital",
    "IN_EQUIP_MULTIMIDIA": "Multimídia",
    "QT_EQUIP_MULTIMIDIA": "Qtd. Multimídia",
    "IN_DESKTOP_ALUNO": "Desktop Aluno",
    "QT_DESKTOP_ALUNO": "Qtd. Desktop Aluno",
    "IN_COMP_PORTATIL_ALUNO": "Notebook Aluno",
    "QT_COMP_PORTATIL_ALUNO": "Qtd. Notebook Aluno",
    "IN_TABLET_ALUNO": "Tablet Aluno",
    "QT_TABLET_ALUNO": "Qtd. Tablet Aluno",
    "IN_INTERNET": "Internet",
    "IN_INTERNET_ALUNOS": "Internet Alunos",
    "IN_INTERNET_ADMINISTRATIVO": "Internet Admin",
    "IN_INTERNET_APRENDIZAGEM": "Internet Aprendizagem",
    "IN_INTERNET_COMUNIDADE": "Internet Comunidade",
    "IN_ACESSO_INTERNET_COMPUTADOR": "Acesso via PC",
    "IN_ACES_INTERNET_DISP_PESSOAIS": "Acesso via Disp. Pessoais",
    "TP_REDE_LOCAL": "Rede Local",
    "IN_BANDA_LARGA": "Banda Larga",

    // PROFISSIONAIS
    "IN_PROF_ADMINISTRATIVOS": "Prof. Administrativos",
    "QT_PROF_ADMINISTRATIVOS": "Qtd. Administrativos",
    "IN_PROF_SERVICOS_GERAIS": "Prof. Serviços Gerais",
    "QT_PROF_SERVICOS_GERAIS": "Qtd. Serviços Gerais",
    "IN_PROF_BIBLIOTECARIO": "Bibliotecários",
    "QT_PROF_BIBLIOTECARIO": "Qtd. Bibliotecários",
    "IN_PROF_SAUDE": "Prof. Saúde",
    "QT_PROF_SAUDE": "Qtd. Prof. Saúde",
    "IN_PROF_COORDENADOR": "Coordenadores",
    "QT_PROF_COORDENADOR": "Qtd. Coordenadores",
    "IN_PROF_FONAUDIOLOGO": "Fonoaudiólogos",
    "QT_PROF_FONAUDIOLOGO": "Qtd. Fonoaudiólogos",
    "IN_PROF_NUTRICIONISTA": "Nutricionistas",
    "QT_PROF_NUTRICIONISTA": "Qtd. Nutricionistas",
    "IN_PROF_PSICOLOGO": "Psicólogos",
    "QT_PROF_PSICOLOGO": "Qtd. Psicólogos",
    "IN_PROF_ALIMENTACAO": "Prof. Alimentação",
    "QT_PROF_ALIMENTACAO": "Qtd. Prof. Alimentação",
    "IN_PROF_PEDAGOGIA": "Pedagogos",
    "QT_PROF_PEDAGOGIA": "Qtd. Pedagogos",
    "IN_PROF_SECRETARIO": "Secretários",
    "QT_PROF_SECRETARIO": "Qtd. Secretários",
    "IN_PROF_SEGURANCA": "Seguranças",
    "QT_PROF_SEGURANCA": "Qtd. Seguranças",
    "IN_PROF_MONITORES": "Monitores",
    "QT_PROF_MONITORES": "Qtd. Monitores",
    "IN_PROF_GESTAO": "Gestão",
    "QT_PROF_GESTAO": "Qtd. Gestão",
    "IN_PROF_ASSIST_SOCIAL": "Assist. Sociais",
    "QT_PROF_ASSIST_SOCIAL": "Qtd. Assist. Sociais",
    "IN_PROF_TRAD_LIBRAS": "Tradutores Libras",
    "QT_PROF_TRAD_LIBRAS": "Qtd. Trad. Libras",
    "IN_PROF_AGRICOLA": "Instrutores Agrícolas",
    "QT_PROF_AGRICOLA": "Qtd. Instr. Agrícolas",
    "IN_PROF_REVISOR_BRAILLE": "Revisores Braille",
    "QT_PROF_REVISOR_BRAILLE": "Qtd. Rev. Braille",

    // DADOS PEDAGÓGICOS
    "IN_ALIMENTACAO": "Alimentação Escolar",
    "IN_MATERIAL_PED_MULTIMIDIA": "Mat. Multimídia",
    "IN_MATERIAL_PED_INFANTIL": "Mat. Infantil",
    "IN_MATERIAL_PED_CIENTIFICO": "Mat. Científico",
    "IN_MATERIAL_PED_DIFUSAO": "Mat. Difusão",
    "IN_MATERIAL_PED_MUSICAL": "Mat. Musical",
    "IN_MATERIAL_PED_JOGOS": "Jogos Educativos",
    "IN_MATERIAL_PED_ARTISTICAS": "Mat. Artístico",
    "IN_MATERIAL_PED_PROFISSIONAL": "Mat. Profissional",
    "IN_MATERIAL_PED_DESPORTIVA": "Mat. Desportivo",
    "IN_MATERIAL_PED_INDIGENA": "Mat. Indígena",
    "IN_MATERIAL_PED_ETNICO": "Mat. Étnico",
    "IN_MATERIAL_PED_CAMPO": "Mat. Campo",
    "IN_MATERIAL_PED_BIL_SURDOS": "Mat. Bilíngue Surdos",
    "IN_MATERIAL_PED_AGRICOLA": "Mat. Agrícola",
    "IN_MATERIAL_PED_QUILOMBOLA": "Mat. Quilombola",
    "IN_MATERIAL_PED_EDU_ESP": "Mat. Educ. Especial",
    "IN_MATERIAL_PED_NENHUM": "Sem Material Específico",
    "IN_EDUCACAO_INDIGENA": "Educação Indígena",
    "TP_INDIGENA_LINGUA": "Língua Indígena",
    "CO_LINGUA_INDIGENA_1": "Cód. Língua 1",
    "CO_LINGUA_INDIGENA_2": "Cód. Língua 2",
    "CO_LINGUA_INDIGENA_3": "Cód. Língua 3",
    "IN_EXAME_SELECAO": "Exame Seleção",
    "IN_RESERVA_PPI": "Cotas PPI",
    "IN_RESERVA_RENDA": "Cotas Renda",
    "IN_RESERVA_PUBLICA": "Cotas Escola Pública",
    "IN_RESERVA_PCD": "Cotas PCD",
    "IN_RESERVA_OUTROS": "Outras Cotas",
    "IN_RESERVA_NENHUMA": "Sem Cotas",
    "IN_REDES_SOCIAIS": "Redes Sociais",
    "IN_ESPACO_ATIVIDADE": "Espaço Atividade",
    "IN_ESPACO_EQUIPAMENTO": "Uso Equip. Comunidade",
    "IN_ORGAO_ASS_PAIS": "Assoc. Pais",
    "IN_ORGAO_ASS_PAIS_MESTRES": "APM",
    "IN_ORGAO_CONSELHO_ESCOLAR": "Conselho Escolar",
    "IN_ORGAO_GREMIO_ESTUDANTIL": "Grêmio Estudantil",
    "IN_ORGAO_OUTROS": "Outros Órgãos",
    "IN_ORGAO_NENHUM": "Sem Órgãos Colegiados",
    "TP_PROPOSTA_PEDAGOGICA": "Proposta Pedagógica",
    "IN_EDUC_AMBIENTAL": "Educação Ambiental",
    "IN_EDUC_AMB_CONTEUDO": "Ed. Amb. Conteúdo",
    "IN_EDUC_AMB_CURRICULAR": "Ed. Amb. Curricular",
    "IN_EDUC_AMB_EIXO": "Ed. Amb. Eixo",
    "IN_EDUC_AMB_EVENTOS": "Ed. Amb. Eventos",
    "IN_EDUC_AMB_PROJETOS": "Ed. Amb. Projetos",
    "IN_EDUC_AMB_NENHUMA": "Sem Ed. Ambiental",
    "TP_AEE": "Tipo AEE",
    "TP_ATIVIDADE_COMPLEMENTAR": "Ativ. Complementar",
    "IN_MEDIACAO_PRESENCIAL": "Mediação Presencial",
    "IN_MEDIACAO_SEMIPRESENCIAL": "Mediação Semipresencial",
    "IN_MEDIACAO_EAD": "Mediação EAD",

    // MODALIDADES E ETAPAS
    "IN_REGULAR": "Ensino Regular",
    "IN_DIURNO": "Diurno",
    "IN_NOTURNO": "Noturno",
    "IN_EAD": "EAD",
    "IN_ESCOLARIZACAO": "Escolarização",
    "IN_INF": "Educação Infantil",
    "IN_INF_CRE": "Creche",
    "IN_INF_PRE": "Pré-Escola",
    "IN_FUND": "Ensino Fundamental",
    "IN_FUND_AI": "Fund. Anos Iniciais",
    "IN_FUND_AF": "Fund. Anos Finais",
    "IN_MED": "Ensino Médio",
    "IN_PROF": "Educ. Profissional",
    "IN_PROF_TEC": "Prof. Técnico",
    "IN_EJA": "EJA",
    "IN_EJA_FUND": "EJA Fundamental",
    "IN_EJA_MED": "EJA Médio",
    "IN_ESP": "Educ. Especial",
    "IN_ESP_CC": "Esp. Classe Comum",
    "IN_ESP_CE": "Esp. Classe Exclusiva",

    // MATRÍCULAS (QT_MAT)
    "QT_MAT_BAS": "Total Matrículas",
    "QT_MAT_INF": "Mat. Infantil",
    "QT_MAT_INF_CRE": "Mat. Creche",
    "QT_MAT_INF_PRE": "Mat. Pré-Escola",
    "QT_MAT_FUND": "Mat. Fundamental",
    "QT_MAT_FUND_AI": "Mat. Fund. AI",
    "QT_MAT_FUND_AF": "Mat. Fund. AF",
    "QT_MAT_MED": "Mat. Médio",
    "QT_MAT_PROF": "Mat. Profissional",
    "QT_MAT_EJA": "Mat. EJA",
    "QT_MAT_ESP": "Mat. Especial",
    "QT_MAT_BAS_FEM": "Mat. Feminino",
    "QT_MAT_BAS_MASC": "Mat. Masculino",
    "QT_MAT_BAS_ND": "Mat. Sexo ND",
    "QT_MAT_BAS_BRANCA": "Mat. Branca",
    "QT_MAT_BAS_PRETA": "Mat. Preta",
    "QT_MAT_BAS_PARDA": "Mat. Parda",
    "QT_MAT_BAS_AMARELA": "Mat. Amarela",
    "QT_MAT_BAS_INDIGENA": "Mat. Indígena",

    // DOCENTES (QT_DOC)
    "QT_DOC_BAS": "Total Docentes",
    "QT_DOC_INF": "Doc. Infantil",
    "QT_DOC_INF_CRE": "Doc. Creche",
    "QT_DOC_INF_PRE": "Doc. Pré-Escola",
    "QT_DOC_FUND": "Doc. Fundamental",
    "QT_DOC_FUND_AI": "Doc. Fund. AI",
    "QT_DOC_FUND_AF": "Doc. Fund. AF",
    "QT_DOC_MED": "Doc. Médio",
    "QT_DOC_PROF": "Doc. Profissional",
    "QT_DOC_EJA": "Doc. EJA",
    "QT_DOC_ESP": "Doc. Especial",

    // TURMAS (QT_TUR)
    "QT_TUR_BAS": "Total Turmas",
    "QT_TUR_INF": "Turmas Infantil",
    "QT_TUR_FUND": "Turmas Fundamental",
    "QT_TUR_MED": "Turmas Médio",
    "QT_TUR_PROF": "Turmas Profissional",
    "QT_TUR_EJA": "Turmas EJA",
    "QT_TUR_ESP": "Turmas Especial"
};

export const CATEGORIAS_RELATORIO = {
    'Identificação e Localização': [
        'NU_ANO_CENSO', 'NO_ENTIDADE', 'CO_ENTIDADE', 'NO_REGIAO', 'NO_UF', 'NO_MUNICIPIO', 'NO_DISTRITO', 'NO_BAIRRO',
        'DS_ENDERECO', 'NU_ENDERECO', 'DS_COMPLEMENTO', 'CO_CEP', 'NU_DDD', 'NU_TELEFONE',
        'TP_DEPENDENCIA', 'TP_LOCALIZACAO', 'TP_LOCALIZACAO_DIFERENCIADA', 'TP_SITUACAO_FUNCIONAMENTO',
        'DT_ANO_LETIVO_INICIO', 'DT_ANO_LETIVO_TERMINO', 'TP_REGULAMENTACAO'
    ],
    'Vínculos e Mantenedora': [
        'IN_VINCULO_SECRETARIA_EDUCACAO', 'IN_VINCULO_SEGURANCA_PUBLICA', 'IN_VINCULO_SECRETARIA_SAUDE', 'IN_VINCULO_OUTRO_ORGAO',
        'IN_PODER_PUBLICO_PARCERIA', 'TP_PODER_PUBLICO_PARCERIA',
        'IN_MANT_ESCOLA_PRIVADA_EMP', 'IN_MANT_ESCOLA_PRIVADA_ONG', 'IN_MANT_ESCOLA_PRIVADA_SIND', 'IN_MANT_ESCOLA_PRIVADA_SIST_S', 'IN_MANT_ESCOLA_PRIVADA_S_FINS',
        'NU_CNPJ_ESCOLA_PRIVADA', 'NU_CNPJ_MANTENEDORA'
    ],
    'Infraestrutura Básica': [
        'IN_AGUA_POTAVEL', 'IN_AGUA_REDE_PUBLICA', 'IN_AGUA_POCO_ARTESIANO', 'IN_AGUA_CACIMBA', 'IN_AGUA_FONTE_RIO', 'IN_AGUA_INEXISTENTE',
        'IN_ENERGIA_REDE_PUBLICA', 'IN_ENERGIA_GERADOR_FOSSIL', 'IN_ENERGIA_RENOVAVEL', 'IN_ENERGIA_INEXISTENTE',
        'IN_ESGOTO_REDE_PUBLICA', 'IN_ESGOTO_FOSSA_SEPTICA', 'IN_ESGOTO_FOSSA_COMUM', 'IN_ESGOTO_INEXISTENTE',
        'IN_LIXO_SERVICO_COLETA', 'IN_LIXO_QUEIMA', 'IN_LIXO_ENTERRA', 'IN_LIXO_DESTINO_FINAL_PUBLICO', 'IN_TRATAMENTO_LIXO_RECICLAGEM'
    ],
    'Dependências e Espaços': [
        'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA', 'IN_SALA_LEITURA', 'IN_AUDITORIO',
        'IN_LABORATORIO_INFORMATICA', 'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_EDUC_PROF',
        'IN_QUADRA_ESPORTES', 'IN_QUADRA_ESPORTES_COBERTA', 'IN_QUADRA_ESPORTES_DESCOBERTA', 'IN_PISCINA', 'IN_PARQUE_INFANTIL',
        'IN_COZINHA', 'IN_REFEITORIO', 'IN_DESPENSA', 'IN_ALMOXARIFADO',
        'IN_BANHEIRO', 'IN_BANHEIRO_EI', 'IN_BANHEIRO_PNE', 'IN_BANHEIRO_FUNCIONARIOS', 'IN_BANHEIRO_CHUVEIRO',
        'IN_DORMITORIO_ALUNO', 'IN_DORMITORIO_PROFESSOR', 'IN_AREA_VERDE', 'IN_PATIO_COBERTO', 'IN_PATIO_DESCOBERTO',
        'IN_SALA_DIRETORIA', 'IN_SALA_PROFESSOR', 'IN_SECRETARIA', 'IN_SALA_ATENDIMENTO_ESPECIAL',
        'IN_ACESSIBILIDADE_INEXISTENTE', 'IN_ACESSIBILIDADE_CORRIMAO', 'IN_ACESSIBILIDADE_ELEVADOR', 'IN_ACESSIBILIDADE_PISOS_TATEIS', 'IN_ACESSIBILIDADE_RAMPAS', 'IN_ACESSIBILIDADE_VAO_LIVRE', 'IN_ACESSIBILIDADE_SINAL_SONORO', 'IN_ACESSIBILIDADE_SINAL_TATIL', 'IN_ACESSIBILIDADE_SINAL_VISUAL'
    ],
    'Equipamentos e Tecnologia': [
        'IN_INTERNET', 'IN_BANDA_LARGA', 'IN_INTERNET_ALUNOS', 'IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_ADMINISTRATIVO', 'IN_INTERNET_COMUNIDADE',
        'QT_COMPUTADORES', 'QT_COMP_ALUNO', 'IN_DESKTOP_ALUNO', 'QT_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO', 'QT_COMP_PORTATIL_ALUNO', 'IN_TABLET_ALUNO', 'QT_TABLET_ALUNO',
        'IN_EQUIP_MULTIMIDIA', 'QT_EQUIP_MULTIMIDIA', 'IN_EQUIP_LOUSA_DIGITAL', 'QT_EQUIP_LOUSA_DIGITAL',
        'IN_EQUIP_TV', 'QT_EQUIP_TV', 'IN_EQUIP_SOM', 'QT_EQUIP_SOM', 'IN_EQUIP_DVD', 'QT_EQUIP_DVD',
        'IN_EQUIP_IMPRESSORA', 'IN_EQUIP_IMPRESSORA_MULT', 'IN_EQUIP_COPIADORA', 'IN_EQUIP_SCANNER'
    ],
    'Dados Pedagógicos': [
        'IN_ALIMENTACAO', 'TP_PROPOSTA_PEDAGOGICA',
        'IN_MATERIAL_PED_MULTIMIDIA', 'IN_MATERIAL_PED_INFANTIL', 'IN_MATERIAL_PED_CIENTIFICO', 'IN_MATERIAL_PED_DIFUSAO', 'IN_MATERIAL_PED_MUSICAL', 'IN_MATERIAL_PED_JOGOS', 'IN_MATERIAL_PED_ARTISTICAS', 'IN_MATERIAL_PED_DESPORTIVA', 'IN_MATERIAL_PED_INDIGENA', 'IN_MATERIAL_PED_ETNICO', 'IN_MATERIAL_PED_CAMPO', 'IN_MATERIAL_PED_BIL_SURDOS', 'IN_MATERIAL_PED_QUILOMBOLA', 'IN_MATERIAL_PED_EDU_ESP',
        'IN_EDUCACAO_INDIGENA', 'TP_INDIGENA_LINGUA',
        'IN_EXAME_SELECAO', 'IN_RESERVA_PPI', 'IN_RESERVA_RENDA', 'IN_RESERVA_PUBLICA', 'IN_RESERVA_PCD',
        'IN_REDES_SOCIAIS', 'IN_ESPACO_ATIVIDADE', 'IN_ORGAO_CONSELHO_ESCOLAR', 'IN_ORGAO_GREMIO_ESTUDANTIL', 'IN_ORGAO_ASS_PAIS_MESTRES',
        'IN_EDUC_AMBIENTAL', 'TP_AEE', 'TP_ATIVIDADE_COMPLEMENTAR', 'IN_MEDIACAO_PRESENCIAL', 'IN_MEDIACAO_SEMIPRESENCIAL', 'IN_MEDIACAO_EAD'
    ],
    'Profissionais': [
        'QT_PROF_ADMINISTRATIVOS', 'QT_PROF_SERVICOS_GERAIS', 'QT_PROF_BIBLIOTECARIO', 'QT_PROF_SAUDE', 'QT_PROF_COORDENADOR',
        'QT_PROF_FONAUDIOLOGO', 'QT_PROF_NUTRICIONISTA', 'QT_PROF_PSICOLOGO', 'QT_PROF_ALIMENTACAO', 'QT_PROF_PEDAGOGIA',
        'QT_PROF_SECRETARIO', 'QT_PROF_SEGURANCA', 'QT_PROF_MONITORES', 'QT_PROF_GESTAO', 'QT_PROF_ASSIST_SOCIAL',
        'QT_PROF_TRAD_LIBRAS', 'QT_PROF_AGRICOLA'
    ],
    'Matrículas, Docentes e Turmas': [
        'QT_MAT_BAS', 'QT_MAT_INF', 'QT_MAT_FUND', 'QT_MAT_MED', 'QT_MAT_PROF', 'QT_MAT_EJA', 'QT_MAT_ESP',
        'QT_DOC_BAS', 'QT_DOC_INF', 'QT_DOC_FUND', 'QT_DOC_MED', 'QT_DOC_PROF', 'QT_DOC_EJA', 'QT_DOC_ESP',
        'QT_TUR_BAS', 'QT_TUR_INF', 'QT_TUR_FUND', 'QT_TUR_MED', 'QT_TUR_PROF', 'QT_TUR_EJA', 'QT_TUR_ESP'
    ]
};
